### ISSUE TITLE
Error running normal scan

### ISSUE THREAD

**Issue by ishikawa13** [skynet0x01/tugarecon#4]
Hi could you please help me with this error?

Traceback (most recent call last):
  File "tugarecon.py", line 190, in <module>
    menu()
  File "tugarecon.py", line 186, in menu
    main(target, output, savemap, enum, threads, bruteforce, args)
  File "tugarecon.py", line 153, in main
    enums = [indicate(target, output) for indicate in chosenEnums]
  File "tugarecon.py", line 153, in <listcomp>
    enums = [indicate(target, output) for indicate in chosenEnums]
  File "/home/tugarecon/modules/tuga_virustotal.py", line 29, in __init__
    self.enumerate(self.response, output, target)
  File "/home/tugarecon/modules/tuga_virustotal.py", line 49, in enumerate
    subdomains = response.json()["data"][subdomainscount]["id"]
KeyError: 'data'

**Comment by skynet0x01** [comment]
Resolved
